FROM python:3.12-slim

WORKDIR /app

# Copy FastAPI app
COPY apps/services/api /app

# Create directory for frontend files
RUN mkdir -p /app/frontend/web

# Copy frontend web files
COPY apps/frontend/web /app/frontend/web

# Copy requirements file
COPY apps/services/api/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
